spring:
  application:
    name:  config-default
eureka:
  instance:
    appname: user-service
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
